[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    dayatkun01/ClearDS1302
build_flags =
    -Wl,-u,vfprintf -lprintf_flt -lm
